name: my_movies
description: "A movie test"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.0
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0
  go_router: ^6.0.9
  google_fonts: ^4.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.12
  readmore: ^2.2.0
  shimmer: ^2.0.0
  stream_transform: ^2.1.0
  url_launcher: ^6.1.8
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.5
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/